---
title: "\"蒙特利尔\"开启\"后京都时代\"——联合国气候变化会议侧记"
#description-meta: "An unofficial paperwork guide for visiting CUNY Baruch College"
#author: "Gang He"
categories: [cn]
date: "2005-12-15"
title-block-banner: false
format:
  html:
    title-block-categories: false
#page-layout: full
from: markdown+emoji
---

**文/图：何钢**

> 梦想和理性是人类前进的双翼。从联合国气候变化会议上可以窥见人类怎样发现一个全球性的问题，如何通过理性的谈判达成共识，并通过组织保障和资金支持实现其梦想和目标的过程，以及在这个过程中，各国政府、科学家、商业企业、非政府组织等利益相关者的参与和博弈。

```{=html}
<!-- 原刊第 19-25 页 -->
```

老城是蒙特利尔最有特色的地方，联合国气候变化会的会议中心所在地议会大厦就在老城旁边，距我们青年代表住的家庭旅馆只有10分钟的路程。 蒙特利尔的冬天很冷，我到的前一天下了第一场雪，会议开始的那一天阳光灿烂，走的时候蒙特利尔又降大雪，之间忽暖忽冷，就像这会议的温度。

## 11月28日

大会开幕。190多个国家的8000名代表，让会场蔚为壮观。自1994年《联合国气候变化框架协议(UNFCCC)》生效以后，缔约方大会年年都开，到今年已经是第11次。 这次会议同时也是《京都议定书》 生效后的第一次缔约方会议。 因此，意义十分重大，各方的期望值也很高。

无论是立于广场的巨型标幅在雪中静静的呼唤“地球母亲凝望着你 (Mother Earth is Watching You)”，还是进门前的大型沙漏，在提醒代表们“时日无多”(Time is running out!)，抑或身着北极能和熊猫服装的志愿者穿梭在人群中散发“I love Kyoto”的贴画，心型的地球是爱的内容，在你等待严格的安检时还给你一个温情的熊式拥抱......这些都给代表们一种关切的氛围，在你奔向谈判桌前提醒你，除了利益，还有地球、还有行动、还有爱!

加方对主办这次会议费尽了心思。主办方特别强调将召开一次绿色的大会，大会计算中心的所有电脑都是用风力发电的电能。而会议所用的纸张，也尽量回收利用，垃圾分类箱更是随处可见。

蒙特利尔市长的致词自豪之情溢于言表，因为这也是《蒙特利尔议定书》签署的地方，同时是《生物多样性协议》秘书处的所在地，它能不能再次成为COP/MOP的里程碑，确实是留给大会的悬念。

突然会议厅的灯全部熄灭，古老的音乐响起，主席台的屏幕上出现了你所能想到的地球美景流转的图片，这是一个名为“大地女神和人类的故事”的短剧，从自然之美妙、地球之神奇，到人类在飓风、烟尘、洪水等等灾难中的挣扎，再到生态的传奇和世界的笑脸，给人强烈的震撼。

大会主席，加拿大环境部长斯特凡•迪翁 (Stéphane Dion) 在宣布大会开幕时希望本次会议取得“有实质性的进展”，因为这是历史的转折，也是历史的开端。他用3个“I”形象生动的说明了这次会议的“历史性重任”：执行(Implement)KP的决议，改进(Improve)UNFCCC和KP的实施，尤其是清洁发展机制(CDM)、适应(Adaptation)和技术转让，以及创新(Innovate)“后京都时代”的履约。

开幕式结束，代表们就要分开会场开始及日持久的谈判“游戏和战斗”，虽然会议之前，大会秘书处已经做了充分的准备，已经形成了各需要讨论议题的草案，但是等待他们的还将有一连串的挑战。

后京都授权 (Post-2012 Mandate)。KP 第一承诺期结束，也就是2012年之后怎么办? 因为它涉及KP第三条第九款的内容，因此也简称KP3.9。KP诞生不久还在襁褓中就遭到了美国的拒绝。为了让美国参与，很多缔约方已经做好了在UNFCCC的框架下来讨论后京都的准备，但考虑到美国反对任何关于Post-2012的讨论，因此KP仍然是讨论Post-2012的法律基础，因为美国在KP中仅为观察员身份，没有发言权也没有投票权。

通过马拉喀什协定 (Marrakech Accords)。KP是UNFCCC的具体执行，而马拉喀什协定则是KP的执行规范，涉及到一系列复杂的协议。MA是长年累月的艰苦谈判才最终完成的，所以任何重新开始谈的可能都必须拒绝，且按计划必须在周三也就是11月30日通过，需要同时通过的还包括已经达成的履约机制 (Compliance System)。

清洁发展机制 (CDM)。CDM是京都三机制之一，已经开始启动并增长很快，因为该机制可以帮助发达国家实现威排义务，技术转让和资金也有利于发展中国家的可持续发展，因此发达国家和发展中国家都对此感兴趣。

资金 (Finance)。缔约方有义务推动一个主要由发达国家资助的关于适应(Adaptation)的科学、技术和社会经济方面的五年计划。同时要确保气候变化特别基金的建立。

尽管在这些关键问题上，缔约方已经达成主要的共识，但仍可能碰到诸如美国、沙特等国的百般阻挠，它们是否能取得实质性进展，所以也就成了这次会议备受关注的话题。注定又是一场漫长而艰辛的谈判，而这仅仅是一个开始。

11 月 28 日当天的 ECO Newsletter 刊登了“蒙特利尔气候谈判将充满挑战”的评论文章，文章指出，这次会议将充满挑战，因为这是历史性的一刻，也是历史的转折点。文章还指出，这次会议将决定《京都议定书》 的命运，也将决定全球气候变化的未来。

```{=html}
<!-- 原刊第 21 页 -->
```

::: {.callout-note}

## UNFCCC会议体系

主要包括COP即《联合国气候变化框架协议》缔约方大会和《京都议定书》缔约方大会 (COP/MOP)，以及SABSTA(附属科技咨询机构) 会议和SBI(附属执行机构)会议。 大会每年一次，而附属机构的会议是一年两次。此外还有各个利益集团，主要有伞形集团、小岛国家联盟、非洲联盟、欧盟、七十七国集团加中国、最不发达国家联盟、石油输出国组织等的分会，和单边或多边会谈等等。一般会由分会讨论协调最终由一个国家来代表该利益集团发言。

除了大会以外，还有青年论坛、市长论坛和和寻求解决方案的世界 (A world of Solution) 等平行事件 (Parallel Events)，青年论坛发表了《我们的气候、我们的挑战、我们的未来---2005蒙特利尔国际青年宣言》，市长论坛发表了《世界城市市长气候变化宣言》，作为特定群体，都对大会表达了了响应和支持。同时各样的边会 (Side Events) 也“你方唱罢我登场”，为各类组织创造了交流和宣传的机会，堪称环境领域的“群英会”。

:::

## 11月29日

大会已经走上正轨。进入议会大厦，代表们不约而同的走向信息中心，拿一份当天的议程，这份每天都厚厚的议程记录了当天的大会小会、边会、新闻发布会等等，从中可以全览一天的大小事件，可以说是听会地图了。

此外，还有几份简报是不可少的，一份叫《生态回声(ECO)》，自1972年斯德哥尔摩环境大会以来就出现在各个大型国际会议上，主要由非政府环境组织编撰发行。这次主要由气候行动网络(CAN) 组织。从 ECO 上可以看到一些关于会议和谈判的经典评论文章。它每天都有一个主题，放在最醒目的位置表明当日的热点和焦点，如29号为"紧急问题 (Urgent Issue)"，其它如KP3.9、非洲等也因谈判的进展出现在这一黄金地段，很是抢眼。

NGO前一天评选的"每日化石奖 (fossil of the day)"也会在ECO上曝光，并和且会配有一段说明文字说明他们是什么原因荣膺当日最差谈判国家的榜首。颁奖的目的在于批评那些在谈判过程中表现最差的国家。每日化石奖"每天晚上六点在展区揭幕，很多人届时会光临现场，听NGO宣读这一结果。在过去的几年中，美国和沙特阿拉伯，因为阻挠谈判进程经常"石"榜题名。这个奖项就像美国电影界的"金酸梅奖"得奖人不会来领取。但是，依然对很多国家形成无形压力和约束。

## 11月30日

《京都议定书》第一次缔约方会议(MOP1)开始。这是一个历史性的开始，因为它表明经过8年努力，《京都议定书》正式步入历史轨道。

迪翁向代表们介绍了《马拉喀什协定》的21项一揽子协议，这其中包括土地利用、土地利用和和森林 (LULUCF)，以及与气候变化的不利影响、CDM的方法学问题和国家信息通报和审议相关的条款，还包括灵活机制和指定量的计算等内容。

巴布亚新几内亚等热带雨林国家提出通过一定的奖励机制减少毁林的方案。因为无节制地砍伐，全球因为砍伐热带雨林每年造成的二氧化碳排放占全球排放的25%。其中巴西、印度和巴布亚新几内亚是重灾区。这些全球绿肺，正由重要的碳汇转变成为温室气体的释放源。这个方案旨在让这些国家减少砍伐，并通过经济激励机制， 补偿其在林业收入上的损失。很多发达国家支持这个方案。但是技术上的一些难题仍然悬而未决。大会主席建议成立一个接触小组 (Contact Group)，由各国进一步在小范围内对这个方案进行磋商。

《京都议定书》生效后，具有国际法的法律效力，批准国的承诺将受到法律监督。 因此德罚机制也成为谈判桌上的重要议题。而沙特阿拉伯这个ECO的"化石"之王，再一次单独提出， 为了让这种惩罚机制更加严肃，应该把它正式列为《京都议定书》的修正案。听起来理由充分冠园堂皇。事实上，如果沙特的提议得到其他国家的支持，后果就是《京都议定书》将回到1997年，需要再一次经过各国的批准，才能生效。这将是一个长达数年的漫长过程。"沙特"之心, 路人皆知，因此几乎所有国家都提议在本次大会上通过有关惩罚机制的决定，使得京都的各种机制尽快生效。

```{=html}
<!-- 原刊第 22 页 -->
```

会议还通过了建立"履约委员会"的决定，由该委员会负责监督和管理缔约方执行《京都议定书》的情况。中国代表团副团长苏伟当选为委员。任何不履行议定书的缔约方从此将为自己不负责的行为承担法律责任。

ECO"今日化石奖"的第一名颁给了美国，因为前一天美国首席谈判代表华兰•享特 (Harlan Watson) 表明不愿看到关于2012年以后谈判的任何进展。而沙特则声称如果他们因为石油税收的减少而要求补偿的问题没有在SBSTA的接触小组中讨论的话，他们将阻止成立任何接触小组，其实就是想要阻止谈判取得实质性进展，沙特的自私要求让其成为该奖的第二名。而为了庆祝《马拉喀什协定》的通过，ECO通知将第二天的“今日化石奖”改成了庆祝会，沙特虽然逃过了一劫，但大概心里也不好受，它的阴谋最终没有得逞。

《马拉喀什协议》的最终通过和附件B国家将履行他们的承诺和义务，这标志着《京都议定书》的全面生效，正式进入具体执行阶段，同时也将启动全球碳市场。这个消息传到讨论KP3.9的会场上，代表们为之一振。游走在会议室和边会的商人，大概也吃了一颗定心丸。今日蒙特利尔阳光灿烂，也许是自会议开始以来，最灿烂的一天。气温有所回升，但依然让人感觉到冷。在启动第二承诺期的谈判等议题上，进展还很缓慢。

## 12月3日

大会中期，攻坚阶段，ECO 今日焦点建立基石。

有NGO说"如果说气候谈判有问题的话，问题就在美国"，但是由于美国的顽固，NGO也逐渐认识到不要在美国身上浪费时间，"除非小布什政府下台，否则美国的立场不会有丝毫改变 "。但同时也认为欧盟应该更具"领导力"。还引用了《孙子兵法》的“将者，智、信、仁、勇、严也”，意即希望欧盟更积极地推动这一进程。

对于KP3.9，虽然谈判始终僵持，但大家都明白现在的任务就是:一是启动谈判程序；二是建立机制；三是确立时间表。七十七国集团加中国的立场是加快谈判进程，设立专门的谈判机构和工作组组织谈判，应该在2008年前确定发达国家第二承诺期的具体温室气体减排指标。《京都议定书》经过8年的艰苦谈判和等待才得以生效，而2008年距2012年只有4年时间，留给各国履行批准程序的时间其实已经非常紧迫了。

中国代表团副团长苏伟在接触小组的磋商中连用3个“如果”发出警告：如果不启动谈判程序；如果不就发达国家2012年之后第二承诺期的具体温室气体减排指标达成协议；如果不能使有关修正案在2012年前生效，那么实际上就是将《京都议定书》置于死地，而这将标志着蒙特利尔会议的失败，也是其耻辱---以后提到《京都议定书》，人们只会想到是蒙特利尔“杀了议定书”。如此清醒的认识，说到了大会的痛处，也给代表们当头棒喝。

会议室内谈判进行得如火如荼，蒙特利尔的中心城也酝酿了一场声势浩大的游行。3号当天下午，当地数千人响应环保组织的号召，冒着凛冽的寒风走上街头，呼吁各国重视解决全球变暖问题。参加游行的人们举着大大小小的标语，如“赶快行动、否则后代将因为我们蒙羞”、“美国，签了吧”、“解决全球变暖问题刻不容缓”等等。各类NGO都在游行中组织相应活动或打出自己的标语。魁北克省环境部长穆克莱尔等加拿大政界名流也参加了游行，大会主席迪翁也对游行表示了支持和声援。

美国当然是游行重要的目标，此前，绿色和平组织、气候危机联盟等5个环保组织向美国驻蒙特利尔领事馆递交了一封有60万美国人签名的请愿书，呼吁布什政府采取行动，加入到控制全球变暖的国际行动中来。从CAN了解到，NGO利用他们在全球的网络，已经联系美国、日本、德国、法国、英国、孟加拉国、巴西、澳大利亚、南非等32个国家的民众，于3日同时在全球100个城市组织类似的游行活动。

这是一场广泛参与的运动，身处其中怎能不感受到会议内外连接世界的热度。回顾环境运动的历史，1972年美国的地球日大游行，这样运动式的事件，是对政府进行施压，对环境组织进行团结和对普通民众进行教育的最好方式，也成为NGO常用的方法，一些有影响力的游行往往成为某一个领域的标志性事件。

## 12月5日

经过一天的休会，会议继续跋涉前行，ECO今天的主题词：改革问题。

各国代表提到CDM下的操作过于复杂，为满足项目的要求，应该简化。在这次会议，非附件1国家也表达了对CDM的不满，他们认为CDM执行理事会(EB)开发的附加工具存在问题。适应、清洁发展机制执行委员会报告、联合履行、资金机制、技术转让、能力建设、《京都议定书》的进度和顺应、联合国政府间气候变化专门委员会(IPCC)有关碳捕获和封存的报告都成为会议讨论的重要议题。

出席会议的近40个发达国家承诺在2006－2007两年间为此机制的运行出资1300万美元，也将大大提高EB的能力建设。此外，联合履行机制(JI)也在本次大会上成立了管理机构，以管理发达国家在中东欧经济转型国家投资温室气体减排项目等事宜。

虽然布什政府令人失望，但是美国公民社会对这次大会的参与却让人振奋。大会的另一重要的平行事件——城市市长论坛也在今天开幕。西雅图市长格雷格▪尼克斯(Greg Nickels)谈到他的城市政府本身如何减少温室气体的排放，同时从社区开始从根源上广泛减排。到目前为止，已有192个城市市长在美国城市市长保护气候协议上签字，他们代表了美国38各州的400万人口，这当中包括一个月前受到台风卡特里娜袭击的新奥尔良市。

本次气候会议上的最大“刺头”是美国。布什政府2001年宣布退出《京都议定书》后，美国一直对国际社会呼吁置之不理。作为全球温室气体最大排放国，美国这种单边主义行径招来欧盟、日本等《京都议定书》拥护方强烈抨击。也遭到NGO组织的一致反对，认为布什是“地球的谋杀者”。有NGO人士说，我们“不是不跟美国玩，而是对布什政府死心了”，但是美国是全球的一大排放国，没有美国的参与难以见效。所以转而向美国的民众寻求支持，NGO非常善于寻求新的切入点。但是作为COP/MOP的谈判就不是这么简单了，代表们在为2012年后的路线图一筹莫展。

## 12月7日

COP和COP/MOP高级别会议开幕。

在欢迎各国部长及代表团团长时，主席迪翁再次提到他在缔约方会议开幕发言时谈及的三“I”：执行《京都议定书》；改进《议定书》和《公约》的运作；以革新迎接未来。但是这次他在每一个“I”后面都加上了“ing”，也就是英文中的进行时，既表示大会已经取得了“实质性进展”，同时还需要“持续不断”的执行、改进和创新。

“关于执行，《议定书》是全球第一个用以解决气候变化的具有约束力的协议，其生效后，缔约方需要制订遵约程序以便完成《议定书》的体制框架。COP/MOP通过了《马拉喀什协议》，为全面实施《京都议定书》铺平了道路。关于改进，缔约方提出了与适应行动有关的若干重要倡议，并正在努力加强清洁发展机制。清洁发展机制需要有必要的资源和能力才能成为有效的工具。关于革新概念，现在急需向世界发出一个信息，让世界了解未来保护气候的措施。蒙特利尔会议必须表明，缔约方愿意按照《议定书》第三条第九款就2012 年以后的承诺开始有意义的讨论。”

加拿大总理鲍尔▪马丁(Paul Martin)演讲非常激动人心，展示了东道国的高姿态，也吹响了《京都议定书》的行动号角，“是为控制气候变化而采取行动的时候了”。对于有些富裕国家却不愿意承担责任，他说“气候变化是全球挑战，因此需要全球响应”。他也点名批评美国“没有任何理由推迟行动”，掌声告诉我们美国是如何不得人心。他也因此呼吁，“为了我们的人民，保护我们的地球，必须找到实现所有期待的意志和道路”，而我们“机会和挑战并存”。

中国代表团团长王金祥在部长级会议上阐述了中国应对气候变化的立场：坚持公约的指导作用；在可持续发展的框架下采取行动；高度重视技术在应对气候变化中的重要作用；正确把握适应与减缓气候变化的平衡；把重点放在具体行动上来。并表示中国“将把节约资源作为基本国策”，“将以全面、协调和可持续的科学发展观为主线，长期把节能和提高能源效率作为国际合作的重点”。

关于KP3.9的谈判也进入了白热化的阶段。本来只能容纳近百人的会议室，挤进去了二三百人，还有人在询问最新的进展，大会的保安不得不挡在门口维持秩序。与之形成对照的是，到下午，部长级会议的大会现场就更显寒酸了，几千人的会场，稀稀拉拉的坐了几百人。每年部长们都会在此表达气候变化如何重要、本国如何重视云云，说些冠冕堂皇的话。但是摆在谈判桌前的，还是各国的利益。因此，嗅觉灵敏的记者和商人对于香饵在哪里是再清楚不过了。

## 12月9日

期待已久，长路漫漫已到最后，大会闭幕。

经过11天漫长谈判，代表们这个时候也有一些疲惫了。而蒙特利尔老城城区的街道也装饰了漂亮的彩灯，商店的橱窗则用灯光各式的礼物吸引人们的眼球，西方“圣诞月”的气氛日渐浓郁。而会议室里谈判代表也在等待最后的突破。很遗憾，ECO最后一天的“化石奖”一二三等奖全部颁给了美国，美国成为本次大会中拿奖最多的国家。

青年们早早为这一天做好了准备，因为这是最让他们激动和期待的一天，他们将有3分钟的事件，也是唯一的机会可以在大会上发言。五位代表分别宣读青年宣言中最为重要的观点，深情地呼吁唤起代表内心深处对于未来的关切，因为“你们来到这里，不也是因为未来吗”？“作为代表，你们同时也是父母儿女和兄弟”。而“今天你们谈判的就是我们的未来”。到最后一句“请注视我的双眼以保证保护我们共同的未来”时，全体青年都站起来了，他们分散在会场的各个角落，用各自的语言重复这一句，会场回荡着青年的声音，也敲击着代表们的被谈判“麻木”的心灵。

克林顿的出现如果不是意外，便是主办方的精心安排。这位号称当时世界上最有权力的前美国总统，当着美国代表团在大会发表演讲说，指责布什的环境政策“绝对错误”。他强调，布什政府所谓“减排影响经济发展”的观点是站不住脚的，通过研发节能技术，美国有能力“在保证经济发展情况下，达到并超过《京都议定书》目标”。他肯定了地方水平上为气候变化所做出的努力，并鼓励确定在可再生能源和其它措施方面更细致的目标，而不是笼统的目标。并希望布什政府与其它国家合作，共同应对气候变化。

克氏的出现，无疑增加了会议的分量，但美国代表并不买帐。谈判还在进行。原定于蒙特利尔当地时间12月9日下午6时闭幕的大会，由于俄罗斯代表团在关于启动第二承诺期谈判的问题上突然提出附加自愿承诺的条件，并要求在KP3.9的谈判中增加针对发展中国家的指南，使得谈判一度陷入僵局。但这一附加条件很不合理，因为如果要增加也应该是KP9中的内容，俄罗斯的反戈让代表们大失所望。

经过大会主席以及相关各方同俄罗斯代表团紧急磋商，终于在12月10日凌晨3时左右达成妥协，大会同意考虑与俄方在有关“自愿承诺”的提议上进行进一步磋商。而直到10日上午6时16分。大会主席迪翁一锤定音，正式宣布，与会代表最终达成一致，同意启动发达国家在《京都议定书》第二承诺期，即2012年后的减排责任谈判进程。至此，会议的预计目标全部实现，3“I”得到了最好的阐释。

那一刻，大会主席迪翁和秘书长金利热情相拥，他们最了解这一锤敲下去的意义。

::: {.callout-note}

## 来自世界各地的青年

11月23日至28日，我有幸作为中国青年代表，和来自全球26个国家的近100名青年代表，一起参加了在加拿大蒙特利尔举行的世界青年论坛。会后，作为这次论坛的重要成果，我们发表了《[我们的气候，我们的挑战，我们的未来——2005年蒙特利尔国际青年宣言](our-climate-our-challenge-our-future-cn.qmd)》。作为《联合国气候变化框架协议》第试一次缔约方大会的平行事件之一，青年宣言成为本次大会特别的声音。

我们来自五大洲的不同国家，从中国到加拿大，从南非到密克罗尼西亚，从北美到西欧，说不同的语言有不同的文化，年龄从18岁到26岁不等，有着不同的专业和工作背景，却都怀着对全球气候变化问题的关注的热情。经过五天的深入交流和激烈讨论，大家从不同角度选择最为重要的话题进行沟通，最终达成一致并投票通过了这次宣言。

:::

