---
title: "全球气候变化政策的多哈站"
#description-meta: "An unofficial paperwork guide for visiting CUNY Baruch College"
#author: "Gang He"
categories: [cn]
date: "2013-03-12"
title-block-banner: false
format:
  html:
    title-block-categories: false
#page-layout: full
from: markdown+emoji
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

(原文发于《世界环境》2013年第1期，并转载于世界环境杂志社网站，2013年3月12日)

文/何钢

本次气候大会的有限进展和成果可归结为两个关键词：差距（Gap），是政治承诺和科学发现的差距，是当前承诺离实现两度温控目标的差距，是会议成果与公众和社会期待的差距；脱节（Disconnect），是美、日、加、俄、新等国家和京都二期的脱节，是现实绿色气候基金与兑现每年1000亿美元融资的脱节，是谈判进程缓慢与气候变化加剧所需的快速行动的脱节。

在形形色色的国际谈判中，气候变化谈判大概是最符合章回体小说风格，精彩纷呈又迂回曲折的谈判了。从2005年蒙特利尔气候大会开启“后京都”的谈判，到2012年多哈气候大会确认“京都二期”，前后长达8年之久。本文试图回顾《京都议定书》以来国际政治经济及能源和排放格局的转变，对气候多哈站进行一些思索，以期讨论气候谈判当中的一些根本问题。

## 多哈成果

多哈可以说是气候变化谈判的中转站，取得了一些积极的进展，也尚有许多亟待回答和解决的问题。本文结合《联合国气候变化框架公约》（UNFCCC）秘书处关于多哈会议成果的发布报告，总结多哈会议所取得的主要进展有以下几个方面。

首先，会议修订了《京都议定书》使其在2012年后继续生效，从法律上确定了京都议定书第二承诺期为8年，即2013年到2020年，从而使得公约和议定书的基本制度框架得以继续，中国代表团发布会称之为“这是多哈会议最重要的成果”。京都议定书的“三机制”，即清洁发展机制、联合履约和排放贸易制度，也将得以继续。从这个角度来说，多哈以会议主席乘人不备临门一脚的方式达成了哥本哈根未竟之业。

第二，会议设立了达成2020年后全球气候变化协议的时间表，即到2015年要通过包括发达国家和发展中国家在内的所有国家的通用气候变化协议。参会方同意加速推动及增强现有行动，以实现2摄氏度的全球温控目标。要在2015年5月前达成新协议的草案，未来几年的谈判任务将非常艰巨和复杂。

第三，推进了向发展中国家提供技术转让和资金支持的新的基础设施，通过了选择韩国作为绿色气候基金的所在地和金融常设委员会的工作计划，绿色气候基金将在2013年下半年启动。确定联合国环境规划署为气候技术中心的领导机构，成为执行公约有关技术机制的实体。发达国家重申将履行到2020年每年筹集1000亿美元支持发展中国家减缓和适应的承诺，但未能提供更多细节。

而对于气候大会的有限进展和成果，笔者把它总结为两个关键词：差距(Gap)，是政治承诺和科学发现的差距，是当前承诺离实现两度温控目标的差距，是会议成果与公众和社会期待的差距；脱节(Disconnect)，是美、日、加、俄、新等国家和京都二期的脱节，是现实绿色气候基金与兑现每年1000亿美元融资的脱节，是谈判进程缓慢与气候变化加剧所需的快速行动的脱节。

## 深刻转变

从1997年通过《京都议定书》到现在，国际政治、经济和排放形势以及能源格局已经发生了深刻的变化。要理解气候变化谈判的个中曲折，离不开解析这个时代的转变。

发达国家受到2008年经济危机的影响，至今经济仍未恢复到危机前的水平，一些国家遭受重创。经济危机使得许多发达国家经济自顾不暇，更难以腾出手来应对气候变化的影响，一些国家经济受到影响，使得经济发展成为政策议程上的首要选项，气候变化退出优先议程，也使其难以兑现对出资绿色气候基金帮助发展中国家应对气候变化的承诺。经济的影响还波及到碳市场的效率，欧洲碳交易市场因为额度过剩，碳价格持续下跌。

两相对照，金砖国家（巴西、俄罗斯、印度、中国、南非）的崛起和发展中国家飞速发展使得全球经济和排放格局发生了深刻的变化。根据国际货币基金组织（IMF），按GDP的2010年现值，发展中国家占全球GDP的比例从1997年的约五分之一上升到2010年的约三分之一，上升了14%。发展中国家碳排放（不包含土地利用的排放）所占比例也从1997年的约50%上升到2012年的约55%。现在的世界与《京都议定书》的世界已有大不同，可以说是国际政治、经济变革对于气候变化政策的现实影响。

与此同时，全球能源格局也发生了巨大变化，虽然还谈不上根本性的变革，化石能源能仍占主要来源，但新能源突飞猛进，页岩气异军突起，全球能源格局开始替代能源的长跑。根据IEA发布的数据，过去十年太阳能和风能成为全球增长最快的两种能源来源，年平均增长率分别为38%和26%，但不可忽视的是，化石能源仍然是增量最大的能源来源，全球煤炭消费的增量主要来源于发展中国家的能源需求。发展中国家为满足快速经济增长的能源需求，成为全球能源消费的主要增长点。

这种转变加深了发达国家和发展中国家在应对气候变化上的矛盾，也使得历史排放的责任与未来排放的增长的趋势叠加到一起，在经济危机的情势下，变得更加难以调和与解决。广为讨论的排放责任分担机制，如历史排放、人均排放和历史人均累积排放，以及基于碳预算法，之所以难以获得广泛的接受，就是这种深层矛盾的结果。发达国家既缺动力，也少意愿完成《京都议定书》确定的减排目标，而在《京都议定书》的框架下，发展中国家既无责任，也没义务进行定量减排，这反映在《京都议定书》的执行上的差强人意，现有的框架下，执行议定书目标出现“胡萝卜不够，大棒没有”的尴尬。要实现全球温控2摄氏度的目标，必须要有发达国家的深度减排，以及发展中国家的有效参与。

## 中国空间

综合不同来源的研究表明，中国在2009年前后已经成为世界第一大排放国，2010年前后成为第一大能源消费国，人均排放亦开始达到并超过世界平均水平，中国尚处在快速城市化、工业化的中期，未来排放增长的压力还将非常大，在国际气候谈判中承受的压力也将越来越大。排放空间就是发展空间，在现有国际机制下，中国可以联合其它发展中国家和利益相关国家，寻找到那些即使没有气候变化，我们也需要做，但是做了对保护气候有益的领域，以此寻求国际机制的协助，在这些领域做得更快更好。

这就是说首先要注重应对气候变化的联动效益，寻求应对气候变化与发展经济、创造就业、保护环境及节能减排的共赢。应对气候变化所需要的革命性技术，不仅可应用在气候变化上，也是我们应对能源危机、保障经济发展、保护环境的必须。中国大力发展清洁煤炭技术，大规模投资太阳能、风电等可再生能源，继续开发水电和核电能新能源，积极探索“页岩气革命”，全面推动低碳交通、低碳建筑、低碳工业和低碳城市的建设，把这些领域作为节能减排的优先发展领域，就是一种自利以“利气候”的共赢发展战略。

气候变化的科学共识越来越得到肯定，但是气候变化的全球影响分布非常不均衡。因此需要坚持气候正义，强调气候公平，表明中国，尤其是贫困地区和气候脆弱地区受到气候变化的影响。二氧化碳是一种全球排放物，这必然要求多边机制和国际合作，而排放与能源、经济的依存关系使得各国在减排行动上备受制约。在坚持公约和议定书的框架的同时，应当开展多种机制探索合作：在多边、双边、区域、地方乃至城市和社区层面、在行业及技术领域进行多层面的交流与合作。

气候变化已经发生，气候变化加剧所引发的自然灾害在频度和强度上都有加强的趋势，而气候变化谈判和全球合作应对气候变化的力度上却徘徊不前，这给适应气候变化提到了更紧迫的日程上来。因此，要特别重视气候变化与能源、水和粮食安全的链接关系，加强海岸带、农牧交错带等气候脆弱带，以及农业区、贫困区、城市区等气候敏感区适应气候变化的能力。

气候变化问题之所以难以应对，也是因为与之关联的能源消耗牵涉一国国民经济的各行各业，也直接关系到每一个地球公民的生产、生存和生活方式。最终将有赖于每一个公民的自觉行动，践行可持续性消费，从而推动社会生产与生活方式的转变。转向低碳消费，鼓励开发新低碳技术、研发低碳产品，从而推动经济转型，形成生产力发展新趋势。消费者作为能源消费的终端，他们的低碳消费选择将促使企业不得不进行技术革新，降低能耗、提高资源的利用率，实行环境友好的生产方式。这是所谓低碳转型的原动力和希望所在。

气候变化谈判的进展还有待各方博弈，还需在接下来的历次谈判中接连“下回分解”，但是应对气候变化的行动就是路在脚下、时不我待了。

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}