---
title: "制定一个大胆的计划"
#description-meta: "An unofficial paperwork guide for visiting CUNY Baruch College"
#author: "Gang He"
categories: [cn]
date: "2009-01-01"
title-block-banner: false
format:
  html:
    title-block-categories: false
#page-layout: full
from: markdown+emoji
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}


美国要带领世界进入无碳太阳能时代还为时未晚，但却需要像二战时那样倾全国之力。

文/丹尼斯·海斯 

在政治当局否认气候科学几十年之后,当选总统奥巴马将在一个碳中和基础建设远落后于欧洲和日本的国家里走马上任。美国曾作为世界可再生能源的领头羊，但现在它已经被那些率先过渡到低碳能源的国家所取代。

还是一个总统候选人的时候，奥巴马就宣称，他打算促进可再生能源，提高能源效率，与气候变化作斗争，减少对外国石油的依赖和创造绿色就业机会。不幸的是，一个新总统必须应付布什最后留下的紧迫的灾难性遗产——增加了一倍的国家债务。我们现在欠我们的孩子超过十万亿美元，纽约时代广场的“国债钟”显示我们外债累累，金融系统的崩溃导致全球性的经济衰退。

那些在过去30年来一直敦促彻底改革国家的能源态势的人，极为了解反对变革的利益联盟的力量。我们在挑战石油、煤炭、电力和汽车业——所有这些都是当前获利可观的行业。我们认为，我们需要危机——一个能源“珍珠港”或能源“人造地球卫星” ——来动员公众支持这样一个意义深远的变革。它可能以中东战争、切尔诺贝利事件，埃克森美孚油轮泄露案的形式出现。但是，这些危机来了又走，并没有让国家能源政策发生明显改观。

但是，现在机会以意想不到的形式来临：一个需要数万亿美元投资才能避免崩溃的金融体系，再加上才华过人的新当选总统、全新看待一切的意愿、民主党占主导的美国众议院和参议院，以及对于改变的强大指令。

避免长期深刻的世界性经济衰退的最有效的方式是大量进行绿色投资，使数百万失业人士重新投入工作。例如，当选总统奥巴马可以明智地在5千万户人家每家投入 6000美元以提高能源使用效率。他已经表达了对建设智能电网的兴趣——通过培训成千上万的人，来取代在婴儿潮中出生、现在即将退休的那批人，以缓解公共事业的窘境。如果联邦政府同意投资500亿美元解救底特律（汽车行业），它应该要求这个重病缠身的行业进行重组，急剧提高燃油效率和对汽车工人、技师的再培训，（使他们能够）了解新技术。

最重要的是，我们需要一个致力于太阳能和可再生能源的全国动员，其规模须与二战时相匹敌——当美国释放出其科学创造和工业力量来支持战争的努力。我们需要卡特总统所说的“道义战争”。

## 重申错过的机会

美国今天的能源形势比卡特总统离任时更糟。自1981年以来，美国石油进口从每年16亿桶跃至37亿桶，年温室气体排放量从47亿公吨二氧化碳增至59亿公吨。

1979年，卡特总统宣布，在2000年之前，美国将至少有20%的能源来自可再生能源。太阳能研究所（后改名为国家可再生能源实验室）处于这一努力的核心地位，我当时在那担任主任。太阳能研究所带领着一个由来自国家实验室和重点大学的杰出科学家和分析师组成的团队，为满足甚或超过20%的目标起草技术和政策的蓝图。

里根总统上台的第一年中途就放弃了这一目标。牙医吉姆·爱德华兹担任里根政府的第一任能源部长，他把太阳能研究所1.25亿美元的预算削减至仅2500万美元，并裁员一半。里根总统下令撤下白宫屋顶的太阳能热水器。

继任的乔治·布什和克林顿，在大量廉价石油的情况下对能源政策摇摆不定，并没有促进提高能源使用效率或把美国经济转向可再生能源。而在过去8年中，美国总统在能源政策上是如此的错误百出，以至于以北极钻探的开始和结束的能源政策一般都不被列入显著缺点之列。我们又该何去何从呢？

## 启动太阳能革命

2008年7月17日，阿尔·戈尔发表了《难以忽视的真相》的尾声。迄今为止他讲话中最大胆的提议是这样的：“我挑战我们的国家去承诺在十年内能实现从可再生能源和真正清洁的碳源中获取百分之百的电力。 ”

令人惊讶的是，一个燃煤公用事业协会发言人乔·卢卡斯，嗤笑戈尔是“非主流”。卢卡斯是正确的，正是那些主流思想把我们推入了现在这个烂摊子。戈尔更勇敢的继承了卡特“道义战争 ”的传统。

“道义战争”到底意味着什么？让我们来看看第二次世界大战。

珍珠港事件后的四年里，美国生产了324750架军用飞机，相比之下其前一年仅生产4000架。美国生产的炸弹比参战双方所有其他国家生产的总和还要多。美国也很快生产了22艘航空母舰，349艘驱逐舰， 422艘潜艇以及88410辆坦克和自行火炮。直到1945年战争结束。

今天，形势甚至比在1941年更为清楚，已经全面参与全球事务的美国，对于全世界为避免气候造成无法弥补的破坏而做出的努力取得成功是必不可少的。如果没有美国的参与，气候灾难不可避免。而一旦美国动员起来，没有什么是不可能的。

此外，正如二战使美国走出大萧条，这场道义战争将为深受经济衰退、通货膨胀、飞涨的债务和越来越不利的贸易平衡困扰的经济注射丰富的养料。

美国调查管理顾问公司（Navigant Consulting）计算出，最近将联邦太阳能税收津贴延长8年本身将创造44万个长期就业机会。在这个经济体中，上个世纪联邦政府给予传统燃料巨大的税收优惠，虽然太阳能减税是一个成熟的传统政策——但远未达到在2020年实现百分之百无碳电力的政策目标，而后者将创造无数就业机会。

私营产业也开始积极行动。前石油大亨T·布恩皮肯斯正在建设世界上最大的风力发电场。通用电气公司，已建成为世界上最大的风力涡轮机生产企业之一，并开始进入太阳能行列。应用材料公司正下订单以建设十亿瓦规模的光伏工厂。有500家工业企业参展2008年10月召开的太阳能国际会议。

成千上万的创业者的目标是成为可再生能源的“谷歌”。谷歌本身也是如此！

事实上，一个最有希望的征兆是，那些打破马贝尔和IBM垄断的企业家和风险投资基金把目光转向了埃克森美孚和皮博迪。自1980年以来我们已经走过了漫长的道路，当时纷争不断的石油公司掌控着大型太阳能，而商业技能有限的杰出科学家们掌握着小型太阳能。这一次，太阳能行业是由寻求接管能源业务的经验丰富的企业家掌管。随着150多个太阳能电池制造公司遍布世界各地——其中许多是由高科技巨头支持的——石油工业再也无法像80年代那样把它们悉数购买然后再关闭。

## 列入联邦优先计划

政府帮助新兴工业取代其根深蒂固的老工业的传统。运河比马匹更有效率而备受鼓励；铁路被视为西进之路；州际公路系统取代了许多铁路的功能。

一些可再生能源（例如光电化学）和存储设备（例如纳米启用超级电容器）将从微型曼哈顿计划对研发的投入大大受益。其它的准备通过大规模生产以降低价格——但他们需要确保一定的市场以得到必要的投资。（计算机芯片之所以从高价位的奢侈品变成便宜的商品，只是因为美国空军和美国宇航局大量购买它们，直到其价格下降到自由市场可以接受的程度。）下面有一系列的联邦政策，结合碳燃料限额拍卖机制，将迎来一个太阳能的革命。

联邦政府采购的目标。联邦政府应大量购买光电器件并在所有的联邦大楼、军事基地和布告栏里安装它们—— 并将这些电力大量并网。我们的目标应该是用迅速、可预见的方法扩大市场，同时不断降低价格。

联邦大量采购计算机芯片用于军事和美国宇航局，推动这些半导体器件销量的增长和价格的降低，直到他们便宜到让私营机构看到了爆炸性的需求。现在这种半导体智能贯穿了我们的整个生活。联邦政府大量采购太阳能光伏电池可能会使得这些设备也将无处不在。

构建一个全国性的智能电网。许多碳中和可再生能源是间歇性或白昼性的。一个弹性智能电网能将实时数据全天候地提供给电网运营商并将彼此的仪表智能化。中碳能源来源和存储的最佳地点都分布广泛。我们需要用全国智能电网联结全国。只有政府可以集合多州通道的权力和传输能力，从而使这样的电网变得可行。所需费用估计约为10年投资4千亿美元。每年投资40亿美元不是个小数目，但请记住，在过去六个月中政府已在一个大的保险公司——美国国际集团——投入了1230亿美元，它可无法提供国家智能电网将带来的这些好处。

认真对待汽车里程数。二战期间，底特律被勒令停止生产汽车而开始制造坦克。今天，底特律需要被责令停止生产“民用坦克”而开始生产汽车。制造商应该能够自由地使用任何技术，（使它们的产品）到2020年1加仑汽油至少能跑50英里，到2030年1加仑汽油能跑100英里——尽管应当优先考虑电力和外接充电式复合动力车，它们也能为电网提供分布式后备存储器。如果美国政府向底特律提供500亿美元左右的资助，帮助它重振雄风并实现这些目标，它也应该给Telsa、Modec、Think、Aptera以及数十个其它有勇气和远见在电动和混合动力车上来挑战底特律的创新公司提供类似激励。如果因我们的税收而扼杀这些改革的推动者，将是悲剧性的。

建造电气化铁路为交通要道。美国几乎是唯一一个没有高速电气化铁路的工业化大国——一个可以无碳城际旅行的超高效模式。如果西班牙和意大利可以做到这一点，美国也可以。

建立严格的国家建筑节能标准。我们可以实现到2025年所有新建筑达到碳中和。建筑师和开发商自愿接受绿色建筑标准的速度之快，显示出对于建造在其50年使用寿命中始终有用的绿色建筑深层渴望。我们必须加强这一势头，以创建高效节能的新一代“生命建筑”。

发展绿领劳动力。扭转气候变化对于失业的美国人再就业具有巨大潜力。最大的就业机会将对那些安装和维护光伏发电和太阳能热电设施，建立和维护风力发电和地热工厂，建造和运营高速铁路系统和智能电网的人开放。

我们需要增加百倍的大学项目（主要是在社区学院）来培训这些新的技能。特别要把重点放在那些在能源转型中失去工作的人（如煤矿工人）和那些城市中的穷人，他们眼睁睁看着自己的就业前景消失在全球化的经济中。

## 但是我们将如何支付这些呢？

最初的刺激措施——以抵御经济衰退和增加就业机会——将不可避免地导致赤字融资。它必须立即开始。我是赤字的坚决反对者，但认识到我们恐怕需要再添加一万亿美元的国家债务，我也深感震惊。但是如果从经济中撤出资金（如税收）而投向政府开支，那么这些刺激因素将无法发生作用。

然而，在两年或者更短的时间里，奥巴马总统可以利用一个非常令人愉快的巧合。这是一个意想不到的“双赢”：在这个厌恶税收的国家中最吸引人的潜在长期收入来源原来是一个气候和能源政策，即经济学家所谓的“上游限额和百分之百的拍卖”。限额拍卖最终将每年产生数千亿美元，并把能源投资从碳密集的燃料，如石油、煤炭、煤变油或气、沥青砂和油页岩等转移出去。与此同时，气候战略是最有可能在不可逆转的损害产生前改变世界能源市场的措施。

## 拍卖和计量每一个碳单元

任何旨在限制温室气体排放的重大计划，必须在二氧化碳进入美国经济的2000个地方（煤矿、油田、管道、港口等）确定排放的上限——而不是林立的烟囱和排气管口。

集中于排放量本身的努力往往注定要失败，因为：（1）排放源太多，难以有效管理；（2）美国定期发生一个保守的、反监管的“圣战”，而气候政策需要一个数百年的承诺；（3）它无法测量，更不用说控制一种混杂着全世界亿万个来源（包括农场和森林）的无色无味气体；（4）创造性的贸易商会找到无数种和一个有着众多（温室气体）“源和汇”的体系周旋的方式。如果你喜欢在“信贷违约风险调换”的63万亿美元和去年其它没有资金着落的信用衍生产品的交易，你也会喜欢为复杂的国际排放量交易设计的新衍生工具。

全球“限额-交易”计划概念上非常简单。但是，我们缺乏实时的知识，更不用说推动它生效和实施的权力。例如，年度二氧化碳排放量的17%来自森林砍伐。几乎所有的森林能以低于在发电厂捕获二氧化碳成本的价格得到保护，因此发电厂运营商将可以通过购买森林来抵消其排放。但是，森林是复杂多样的：千差万别的碳吸收率，甚至“受保护的”森林偶尔会遭受森林火灾。森林通过蒸发和反射率以及碳储存来影响气候；总的来说，保护极地寒带森林中实际上使地球更温暖，而不是更凉爽。即使在森林保护显然有利于气候的地方，我们如何保证一片在巴布亚新几内亚的森林能永久得到保护？

一个更好的方案当然是在碳燃料进入经济环节时实施碳许可证和使用其他手段来维护森林和农场。在一个“限额-交易”制度中，除非卖方持有它所包含碳含量的许可证，否则在美国出售任何一个单位的化石燃料将是非法的。在碳许可证签发数量的设定上——从而确定有多少煤，石油和天然气可以进入经济——政府将建立一个绝对的、容易执行的排放量上限。（这样一个系统是美国太阳能协会给111届国会的一部分政策建议）。

通过每年减少许可证拍卖的数量，政府可以保证其二氧化碳排放量达到预期目标：零燃料，零排放。

使用碳基燃料的公司将确切地知道，从现在开始5年到10年内燃料的提供将减少多少，然后他们可以相应地调整自己的投资和制造工艺。

最为关键的是，所有碳许可证是被拍卖——而不是分发。在欧洲，排放许可证被分发给碳的大用户，以缓解他们向新贸易制度的过渡的压力。这使最严重的污染者获取暴利，惩罚了那些已经在高效率的新工厂和可再生能源方面投资的公司，并可能导致欧洲不能实现其京都目标。

与此相反，拍卖百分之百所有碳许可证将是公正和透明的，有利于那些自愿减少其碳使用而需要较少燃料的企业，消除顽固公司幕后的特殊利益诉求。

如果国会担心在这脆弱的经济时期对主要工业产生灾难性的破坏，可以第一年拍卖足够的许可证以减少前一年消费量的百分之一（所以许可证的价格将非常低），并让系统启动。可以第二年减少百分之二的许可证，然后在经济稳定下来的随后几年里减少百分之三甚至更多。

除了精确减少温室气体排放量，戒绝美国对外国石油的依赖和加快投资的效率和可再生能源来创造绿色就业机会，一个上游限额-拍卖系统最终每年将产生数千亿美元的收入。

由于拍卖会从经济中吸引资金，拍卖的运作需要至少几年的时间，而且第一年的上限可能是相当松散的，它不会充当短期经济刺激剂。然而，在4到8年的范围——一个当选总统奥巴马极感兴趣的时间范围——它将把明智的气候和能源政策与稳健的财政政策结合起来。

在更长的时期里，拍卖的收入可以用来建立一个全国的“智能电网”，以协调电力间歇性和白昼性的来源；建设可以使用无碳燃料高速电气化铁路（不像飞机那样）；保证太阳能技术和其他后碳经济的新兴行业拥有广大的联邦市场；以及大力投资提升联邦研究。为了弥补拍卖带来的轻微衰退的情况，部分收入应当用于资助绿领就业培训项目和造福贫困群体的医疗改善或其他项目等。

## 因此，结论如下：

美国有着无与伦比的科学和工程优势，强大的财政实力，丰富的自然资源，一个民主的政治制度和创业文化，非常适合帮助领导世界进入一个富强的碳中和时代。与其花纳税人的钱用于解救一群被超额支付的、管理不严的投资银行、经纪公司、抵押贷款公司和保险公司，不如用其一小部分迎来一个以太阳能为动力的时代。

让我们创造一种政治候来允许——并保证——奥巴马总统和民主党控制的国会利用好这个机会。浪费（作为转机的）危机是可怕的事情。

作者简介：丹尼斯·海斯是查尔斯格里利艾博特奖获得者，美国太阳能学会的研究员和董事会主席。他是布利特基金会主席和国际地球日网络名誉主席。卡特政府时期，海斯是联邦太阳能研究所（现称国家可再生能源实验室）主任。本文大量引用了海斯发表于在线杂志《耶鲁环境》6月刊的文章。本文刊登在Solar Today，2009年1/2月刊。

(翻译/魏可钦  审校/何钢)

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}