---
title: "页岩气革命的冷思考"
#description-meta: "An unofficial paperwork guide for visiting CUNY Baruch College"
#author: "Gang He"
categories: [cn]
date: "2012-08-01"
title-block-banner: false
format:
  html:
    title-block-categories: false
#page-layout: full
from: markdown+emoji
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}


(原文发于《南方能源观察》2012年8月刊)

文/何钢

天然气因其热值高、流动性好、相对其它化石能源污染物及碳排放较少，是化石能源中的清洁能源，有“碳氢能源贵族”之称，2011年占到世界一次能源消费的24%。而页岩气作为天然气的一种，资源量巨大，进入21世纪后因技术突破而横空出世，很快就引发了能源业界的震动，甚至被认为掀起了一场“页岩气革命”。

据美国能源信息署（EIA）2011年发布的《世界页岩气资源》评估，美国页岩气技术可开采储量达24.4万亿立方米，从2000到2010年间，美国页岩气的产量增长了12倍，已经占美国天然气产量 的25%，预计到2035年上升到45%左右。从全球来看，其它32个国家的48个页岩气盆地达160万亿立方米，加上美国的储量总量达185万亿立方米。美国总统奥巴马把页岩气比作“天然气世界的沙特阿拉伯”，并表示其政府将致力于页岩气的安全开发以保障近百年的能源供应。

中国也对页岩气寄以厚望翘首以待。页岩气发展规划（2011-2015 年）显示，中国页岩气可采资源量预计为25万亿立方米，此前有数据显示为31万亿立方米，综合不同来源，可采资源量介于25-31万亿立方米。根据国土资源部油气资源战略研究中心全国页岩气资源潜力调查评价及富集有利区优选工作，到2020 年页岩气探明可采储量约2万亿立方米，产量1000 亿立方米，页岩气将占天然气消费比重的26%左右，成为我国天然气能源的重要支柱。

这样的前景看来是如此诱人，但发展的路上却充满不确定性和甚至是“陷阱”，本文将从资源经济可开采潜力，技术储备，管理体制，健康、安全与环境风险，以及对新能源和气候变化政策的影响几个方面来探讨“页岩气革命”不容忽视的另一面，以期增加对页岩气的认识与思考，并在开发的过程中重视可能产生的问题。

## 资源详查需确认经济开采储量

页岩气是埋藏于富有机质的泥页岩及其夹层当中，以吸附或游离状态赋存的非常规天然气。页岩气之所有成为“革命”，最主要有两条：一是资源储量巨大，二是由于钻井技术的进步使得开采成本急剧下降。对于中国而言，现有资源量预估一是来源于美国EIA的评估，二是来源于已经开展的“全国页岩气资源战略选区及评价”工作的预测量。两者都是根据地质条件作出的预测评估，仍然缺乏地质勘探及钻井资料详查的数据支撑，中国最终可开采的页岩气资源，在目前恐怕还是个未知数。

我们还需区分资源量、探明储量、技术可开采储量和经济可开采储量的差别。根据《联合国化石能源和矿产资源分类框架》，资源的可采性受到三个因素的主要影响：地质认识程度、矿场项目状态与可行性，以及经济与商业存续性，分别可对应探明储量、技术可开采储量和经济可开采储量。虽然这三者的关系随着技术与社会经济条件的变化也是动态的，但是资源基础要转化为技术可开采储量，并最终被开采的经济可开采储量，每一层都要打个大折扣。

笔者写作此文之时，EIA公布美国天然气的期货价格为2.724美元/mmBtu，相当于0.6元人民币/立方米，比一年前的同一时间下降了1.209美元/mmBtu，降幅达30%。自2008年金融危机后美国天然气一直呈下降趋势，页岩气的产量增加更加剧了这样的趋势。天然气价格下降，使得在原先价格如4美元/mmBtu评估下具有经济开采价值的页岩气将不具备经济可采性，也使得预计最终可采储量显著下降。中国天然气市场仍是一个短缺的市场，但长期需考虑能源价格对于经济可开采储量的影响，做好风险评估。

此外，资源条件也需开采条件和基础设施的支撑，其中最重要的就是钻井的数量。页岩气井的产量下降曲线非常陡，根据对美国5个主要产区的调查，一般5年内新开井的产量就已经接近枯竭或已经枯竭。所以产量要跟上预期的速度，钻井的速度必须超过产量增长的速度，据油气市场分析网络《油桶》（The Oil Drum）跟踪报道，近期新井钻探增加速度已经在放慢，与此同时，高产的“风水宝地”（sweet spots）也逐渐被相对低产的区域代替，这对未来页岩气的生产将有显著影响。

## 技术创新合作开发需形成生态系统

技术进步，特别是水平（定向）钻井技术和水力压裂技术的突破是页岩气产量突飞猛进的决定性因素。页岩气因埋藏的页岩基质渗透率低，勘探开发非常困难，传统的钻井必须经过酸化、压裂等储层改造才能获得相对较高的产量。

以水力压裂技术为核心和页岩气开采技术是一连串技术过程的组合，包括压裂、水平（定向）钻井、三维地质成像、加密钻井等。这些技术在中国的起步较晚，目前主要依靠国外公司提供的服务，也有尝试通过合作开发逐步学习自主掌握。但技术创新应用及政府、企业联合创造的技术与市场生态系统却非一朝一夕之功。

页岩气技术的突破发轫于美国，其成功得力于有创造性的企业家群体，也得力于专业懂行的政府，更成于技术创新、密切合作的中小企业网络。

美国的页岩气技术创新以及勘探开发主要由中小公司推动，企业家精神的最大程度发挥。据《经济学人》杂志报道，页岩气之所以有今天， 企业家乔治·米切尔（George Mitchell）功不可没，他聚10年之功，费6百万美元之巨，所有人都说他在浪费时间和金钱，而他坚持下来，改进了液压碎裂钻探技术，使得深埋的页岩气可以经济开采，并为业界广为采用。

与此同时，诚如The Martec Group投资管理咨询有限公司能源电力总监曹寅点评，美国能源部（DOE）的角色也至关重要，DOE制作了美国第一份公开页岩气资源技术可开采储量报告，打了全世界第一口水平空气井，还领导开发了压裂微震制图测绘技术。同企业一起开发了多段水力压裂技术，电磁随钻测量技术，定向空气锤技术等，为企业提供了信息支持，也为行业技术积累创造了条件。

技术一旦突破，中小企业承担风险的能力较强，对市场反应敏捷，很快抢滩页岩气的前沿阵地。目前美国有数千家页岩气相关技术服务公司，有 85%的页岩气产量由中小企业生产和创造的。这些油气类的专业服务公司，规模小相对灵活，门类齐全、专业化程度高，具有强大的技术能力，能自主研发装备。页岩气开采当中的水平钻井和多段压裂等工程乃至完成开采后的环境清理，主要就是有这类专业技术服务公司完成的。

## 治理体制亟待理顺

页岩气作为一种非常规天然气资源，目前我国实行的管理体制有两个突破：一是批准页岩气成为我国第172 个矿种，以便采取独立于传统油气资源的管理机制。二是开展了页岩气探矿权出让招标，引入市场机制，对页岩气资源管理制度进行创新。但由于现有能源管理体制分散且缺乏协调，加上与传统油气资源在矿业权及管理权上的重叠，利益分配和系统衔接将有一系列的挑战。

页岩气的治理体制有以下几个层面：矿权管理体制，投资开发体制，基础设施建设体制，税费征收体制，环境监管体制等。未来资源研究所（Resources for the Future）2011年启动“页岩气的风险和监管”项目，评估和探索页岩气监管的最佳实践。调查31个州，涵盖页岩气开采的全过程，包括场地开发和准备，钻井和生产，废水存储与处理，封井和废弃，监察和实施，及其它如税收政策等等。

2012年俄亥俄州州长提议征收页岩气开采的“压裂费”，同时降低收入税税率。加州大学圣地亚哥分校助理教授张俊杰博士评论说“这是一项非常好的能源环境政策，既内部化了页岩气开采与使用造成的环境和健康成本，同时也降低了其它扭曲税，很有双重红利的意思”。对于有页岩气藏所在州/地区，这样的政策用于建立自然资源基金或者社会福利基金，用于该州的自然资本和居民福利进行再投资。

把税费、严格的污染处理和环境监管、其他风险的监测、响应等算在内，页岩气的综合成本也将相应上升，需要把这些外部成本内化，才是页岩气的真实成本，有利于页岩气的持续发展和高效利用。理顺治理体制在于明确页岩气的利益相关方的利益协调和分配机制，风险分担机制和应急相应机制，而真正受影响的地方社区也应当享有高于本州居民资源红利的补偿。

## 健康、安全与环境风险如影随形

如果说资源可以通过更好的勘探和普查来完善，技术也可通过合作开发来学习和掌握，而“大规模”开采页岩气所造成的健康、安全和环境影响则更为长远和深广。水力压裂技术的环境影响主要有以下几个重要的方面：对地壳的冲击造成的小型乃至中型地震；页岩气开采对于当地社区人群健康的影响；对地下水的影响。

为研究页岩气开采诱发的地震，美国国家研究委员会专门发布《能源技术引发潜在地震》报告表明：水力压裂钻井过程引发地震的可能性较少，但废水注射回灌造成的地震可以观察到，如果再加上碳捕获与存储（CCS），则风险更大。在阿肯萨斯，一些小镇因为地处地壳断裂带，再加之受到附近页岩气开采的影响，一年内竟造成了上千次的小型地震。这些地震虽然震级不大，有些甚至感觉不到，但是由此诱发的二次灾害却造成生命财产的损失。

2010由乔什·福克斯（Josh Fox）指导的纪录片《页岩气之地》（Gasland）调查了页岩气开采尤其是水力压裂技术对当地社区的影响，引发了美国全国性的争论和关注。根据在迪莫克（Dimock）、宾西法利亚州、科罗拉多州和怀俄明州的实地采访，这些地方都是页岩气开采的热点地区，当地居民承受了因此带来的各种病痛，如头痛、恶心、牲畜生病、井水污染、自来水因富含天然气着火、神经病痛、甚至肿瘤和脑损伤。

开采页岩气所赖水力压裂技术，需要巨量水资源和化学物质而造成污染。目前页岩气井水压裂常用的压裂液有减阻水压裂液、纤维压裂液和清洁压裂液。以减阻水压裂液为例，其水和砂组成成分占99%以上，酸、减阻剂、表面活性剂、凝胶剂、防垢剂、抗菌剂、缓蚀剂、支撑剂等添加剂占1%左右。这种液压流体含近600种化学成分，一口井约需上万吨水，大部分废水渗漏或回灌。

英国皇家工程院组织评估英国页岩气开采的健康、安全和环境影响，发布《英国的页岩气开采：水力压裂技术评估》，页岩气开采过程中，地表操作的环境风险是最大的，需要密切监测压裂延伸的，以及低于含水层下的水力压裂，最大程度的保护钻井的完整性，减少对于地下水的影响。页岩气的开采包含了钻井、井上基础设施建设、释气处理、砂岩开采、和重型装载，需要全过程的风险管理和监管，以防范和应对页岩气开采过程中的健康、安全与环境风险。

## 对新能源和气候政策的影响

即使十分安全地进行页岩气的开采，从开采到输运的每一个过程都受到严格的控制，没有人受到环境和健康的影响，页岩气的“革命”还可能带来一个更为长远和深刻的影响，那就是页岩气可能在短期减缓了温室气体的排放，却没有摆脱甚至加剧了对于化石能源的持续依赖，可能推迟甚至腰斩已经曙光初现的“新能源革命”。

天然气的排放强度是煤炭的二分之一，比石油低30%，而其硫化物和氮氧化物的排放几乎可以忽略不计，因而被视为“化石能源当中的清洁能源”。在美国，许多电厂煤炭和天然气作为燃料可以相互替代，页岩气的大量开采以及价格下降的优势，使得天然气“替代煤”成为可能。加上美国联邦环境署严格的排放监管，使得天然气发电更有竞争优势。在美国新规划的电厂多为天然气发电。因为页岩气大量替代煤，预计2012年美国二氧化碳排放将是20年内最低，相当于1992年的水平。

但也有一个好消息，天然气发电具有调整灵活，反应速度快的特点，因此，在大规模储能尚不具备商业可行性的条件下，天然气是低成本整合可变（Variable）的可再生能源的利器。在美国德州、加州等风能资源丰富的地区，天然气发电已经作为更多吸收可再生能源的调用发电能力。由此可见，页岩气更像是一把双刃剑，它降低了发电的成本，让可再生能源的竞争力受到挑战；但同时，它也使得整合新能源的成本降低，使得可再生能源更具竞争力。

页岩气被称为“通往低碳能源的桥梁”，意指页岩气仍然是一个过渡能源，对岸是可再生能源等清洁能源，而如果页岩气造成了新能源发展受损，那可能就称为无头之桥（Bridge to nowhere）了。对于中国以煤为主的能源结构，页岩气或许提供了一个调整能源结构，减缓排放压力，整合飞速发展的可变新能源，实现温室气体排放控制目标的好的机会窗口，如何利用好页岩气的这个特点，相应调整新能源发展战略，是研究者和政策制定者都需要思考的问题。

## 积极准备防范风险迎接革命

页岩气革命是一个全球性的能源现象，而页岩气的潜力要得到充分发挥和合理利用，还需要我们从信息准备、技术突破、健康监管、系统整合和战略协同等方面入手，积极准备及防范风险，在与页岩气革命握手的同时，铺就通向低碳未来的道路。

*本文受益于作者微博\@何钢HG 标签为#页岩气冷水#的讨论，特别致谢微友：\@涂建军KevinTu \@shuwua \@盈川兄 \@芝加哥学派 \@Stanford于洋 \@Armand_Cao \@樱桃大丸子yyy。作者系加州大学伯克利分校能源与资源小组博士生。

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}