---
title: "读书《阳光底下的新鲜事：二十世纪环境史》"
#description-meta: "An unofficial paperwork guide for visiting CUNY Baruch College"
#author: "Gang He"
categories: [cn]
date: "2008-02-15"
title-block-banner: false
format:
  html:
    title-block-categories: false
#page-layout: full
from: markdown+emoji
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

阳光底下的新鲜事：二十世纪环境史

Something New Under the Sun: An Environmental History of the Twentieth-Century World


作者：约翰·麦克尼尔（J.R. McNeill）

出版商：W. W. Norton

出版时间：2000年1月
 

麦克尼尔这部力作的核心思想是人类活动在20世纪以前所未有的速度和尺度改变了地球的面貌。虽然这一观念并非麦氏首创，但麦克尼尔在书中最开始就利用历史的宏观叙事和数据曲线介绍了1500年来人类经济的增长，以及从公元前1万年来人口的增长和能源使用的历史，生动说明了20世纪的一个特殊事实，即人类开始主导地球环境。

作者抓住20世纪环境发展的这一特点，在本书的第一部分作者用大量的数据和丰富的案例，叙述了岩石圈和土壤圈、大气圈、水圈和生物圈因为人类的活动造成的严重生态环境问题，如水土流失、土壤污染、城市空气污染、区域和全球大气环境问题、水污染、水退化、以及生物多样性和森林以及鱼类的逐渐消失和生物物种的入侵等等。

分领域对于环境问题分析的著作文章汗牛充栋，但作者深厚的历史功底和对环境史重要人物和事件的挖掘，使得本书阅读起来既有历史感故事性，又有现实感趣味性，作者并不是堆砌数据和铺述案例，而是从数据中分析趋势，在案例中寻找规律，比方说书中对肥料和制冷剂的发明所带来的影响和后果的分析，突出了人物和事件在环境史上的地位和作用，读来让人耳目一新。

作者不无忧虑的谈到，人类的影响已经渗透到了地球最小的尺度和最大的尺度，作者用生动的比喻，认为地球的原本和谐的“圈层音乐”，因为人类掺杂了噪声，受到了极大的撞击，甚至无法继续上演。麦克尼尔继续挖掘了这种变化的驱动力：人口增长和城市扩张；能源、工具和经济；意识形态和政治。毫无疑问，要从全球角度来阐释环境变迁的动力并不是一件容易的事情，也是一件极为危险的事情，但是如果抓住一些关键因子，对于增加我们对于环境的理解，却有着提纲挈领的作用。

本书涉及的广度非常大，全球不同区域、不同的环境问题等等都有机的结合到作者的历史叙述当中去，但是也正因为如此，作者无法进一步阐明其他文化因素，如种族、文化、宗教、性别等在环境转变中的影响；也不可能深入到某一个地区，将书中谈到的环境驱动力结合到特定的时代、人群和地方。环境史归根到底是人与自然的历史，或称“人地关系”的历史，对于人和地这两个复杂巨系统的耦合，环境史恰是两者的交互，简化的抽象可能丧失两者作用的丰富内涵。

麦克尼尔认为今天的社会和政治结构十分危险的依赖稳定的人与自然的作用，就像适应了自然千百年的“老鼠和鲨鱼”，依赖稳定的气候，丰富的水、能源等资源，以及持续的人口和经济增长，但恰恰是人类自身的活动打破了人与自然的平衡，因而也破坏了人类赖以生存的“生命支持系统”。因此，麦克尼尔在本书的最后反思20世纪人与环境的历史，希望人类真正了解自身与环境的过去，寻求人与自然的平衡，从而适应人类所面临的挑战。（何钢）

作者简介：麦克尼尔是乔治敦大学历史学教授，该书获2001年世界历史学会图书奖。

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}