---
title: "站在世界边缘的思考"
#description-meta: "An unofficial paperwork guide for visiting CUNY Baruch College"
#author: "Gang He"
categories: [cn]
date: "2010-03-08"
title-block-banner: false
format:
  html:
    title-block-categories: false
#page-layout: full
from: markdown+emoji
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

一直想写点啥说说盖斯·斯帕斯(Gus Speth)的新书《世界边缘之桥》（The Bridge at the Edge of the World），但是一直拖着，直到被通知得提前还书，赶紧写点。

这本书是断断续续读完的，按照思维训练，就是如果要用三句话来概括和介绍这本书的话：Speth教授在这本书想呼吁的是，不管现在的环境活动家多么努力甚至狂热地想要阻止目前环境退化的趋势，这个挑战已经太广泛而深入以致目前的人类系统将无法应对。因此，为了保护我们赖以生存的地球，我们必须扭转这种趋势的根源：美国式的消费型资本主义。最后，他提出来，要重新认识到环境问题与其它人类福利如健康、自由、和平、稳定及社区等的联系，推动人类生存方式的大转型。

书中开篇就引用了斯黛芬(W. Steffen)在《全球变化和地球系统》中的经典环境16图，即工业革命以来，人类社会人口、GDP、FDI增长的曲线，1950年后几成指数增长，与之相应人类水的利用、能源消耗、CO2排放、鱼类和生物多样性的消失与灭绝等也大幅增长。人类对于自然和地球的超常规影响，使其到了崩溃的边缘，因而作者“站在世界的边缘”思考，认为这是一个系统的失败。

而这一切的根源，他认为在于失控的资本主义，注意是“失控的”。资本主义创造了巨大的财富，但也前述问题的“万恶之源”。因为资本主义不同于其它的经济体即增长驱动，天然的扩张和追逐利润。首先，资本主义是内生有指数增长的冲动；其次，利润左右资本家的行为；第三，强调扩张，效率和过度膨胀的商业化；最后，注重眼前超过未来，重私人利益多于公共利益。而社会的组织也为围绕资本建立，因为我们现在理解的资本主义也是无能支持环境的可持续发展。这听来颇像马克思主义的环境篇，不过分析的逻辑却是不可忽视的事实。

而从70年代发源的现代环境运动也有其自身的局限。现在的环保主义是关于环境问题的陈述和环境规制的采用；是现实的和渐进的；倾向于处理结果而非寻找原因；相信问题可以在可接受的成本解决；集中在环境部门本身寻找办法；而非集中在政治活动和草根运动；寄托环保当局来解决问题。这些分析我不完全同意，比方说当代环境运动恰是从草根发起的。但已经需要呼吁环境保护2.0来应对当前大量、复杂、环环相扣和深刻的环境挑战，关于这一点，Speth先生其实在几年前有一个很好的总结，参看我翻译的《问题的核心》。

Speth于是乎提出来环境的“大转型”，其中很多是环境经济学探讨的内容。首先是要深入资本主义运行的根基——市场，使得败也市场，成也市场，市场本身是无辜，看人类如何驾驭它。所以建立新的市场，选择正确的技术、形成正确的价格、从而建立正确的环境。这这一切离不开政府这只有形之手的参与，建立激励、标准、管制等等。我很好奇他如何定义“正确”的含义，而政府又如何知晓何为正确呢？外部性也许不难找到价格，而生态系统服务，文化、物种基因等等的定价却恐怕仍是棘手和头疼的难题。

再来腰斩资本主义的妄想症：无止境的增长。而这个增长是一个无就业、无情意、无发声、无根基和无未来的增长。所以他提出来要套住这个增长怪兽的马龙头。也许我们发展的目标一开始就是错的，我们不是片面追求GDP和经济增长，而是全面追求GDP 和经济增长，而忘了GDP膨胀也好，经济增长也好，都是为了人的幸福！这也是最有意思的讨论，用什么来衡量我们的幸福。金钱？事实上过了一定限度，幸福与金钱无关。而超越GDP，虽然已有人类发展指数的采用，但仍有可持续经济福利指标(ISEW)、真实进步指标(GPI)、社会健康指标(ISH)等等的探索。甚至说人类幸福指数(HHI)。总而言之，真正的发展乃要增进人类和自然的福利。

其它的重要转型还包括改变消费主义的商品观念，他提出来“够用就好，而不必更多”，可是多少算够？消费是市场的源头，一方面有人认为，消费者不知道自己需要什么，你生产什么，他就买什么；另一方面，绿色消费理念的引入和接受，消费者逐渐成为一种驱动市场变革的力量。说到底，如果消费者选择绿色，企业便不得不向绿色转型。问题是消费者相对企业是个弱势群体，还需要创新的政策工具的帮助，这在《食品公司》的纪录片中有很有价值的讨论。因而，企业社会责任的塑造，公共基金的建立，在全球化的背景下绿化企业。升级“万恶”的资本主义变成“向善”的资本主义。

可是这样的“美丽新世界”不会自动出现，而Speth先生也未因之悲观，他提出来大转型的温床和种子在于新的意识和观念、新的全球和地方政治。他用生动的语言，有梦想有憧憬，同时也有生动的案例，有行动有突破。自然、未来、系统、精神、相互依存，这样的词汇是环境主义者喜欢的，可是另一方面近在哥本哈根，利益和强权从来就没有离开过国际政治的角逐。也许，这就是环境的魅力，是梦想和现实交锋最强烈却也相爱最热烈的地方，通过一系列自上而下与自下而上的努力，我们不只是听到春天的声音，而是走在春天的田野上。

Speth写书的时候应该还是耶鲁大学森林与环境学院的院长，我喜欢他倒不是因为他是院长，而是他的丰富的环境履历和思考，他曾经担任联合国发展署的主任，曾任白宫环境质量委员会主席，并创办了两个环境领域全球知名的NGO和智囊团：世界资源研究所（WRI）及常和发改委的简称搞混的美国自然资源保护协会（NRDC）。他是否创办过自己的公司，我未得而知，但是这当中的任何一个经历，都足以在环境领域建树，而他创造了森林。此书的出版恰值他从院长离任，以此作为他告别环境生涯的一个总结，也算是一位把一生奉献给环境的智者、思者和行者的思索与追问：在世界的边缘搭建一座通向未来的桥梁。（何钢）

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}