---
title: "问题的核心"
#description-meta: "An unofficial paperwork guide for visiting CUNY Baruch College"
#author: "Gang He"
categories: [cn]
date: "2026-02-01"
title-block-banner: false
format:
  html:
    title-block-categories: false
#page-layout: full
from: markdown+emoji
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

（此译文连同原文将发表在2006年第二期的《世界环境》）

耶鲁森林与环境学院院长 詹姆斯·盖斯·斯帕斯

美国很多环境院系都把培养专业的环境管理人员作为其主要使命。耶鲁森林与环境学院的大多数硕士生都在攻读环境管理学位。那么到底什么是环境管理呢？以我之见，环境管理是促进人类活动与人类赖以生存的自然界和谐发展的一项新事业。我还要强调，环境管理是当今世界最重要的事业。

尽管有关环境退化的种种预测骇人听闻，但我们确信我们终将赢得这场关系到人类未来的战争。

——斯帕斯 院长

这似乎有些危言耸听，但我相信，在不久的将来我们就会深切地感受到这一点。最近几十年来人类活动迅猛扩张，我们即将面临一个全新的时代，环境管理终将成为世界各国政府和人民最优先考虑的问题。

首先，要认识到环境破坏已经相当严重：世界上一半的热带和温带森林不复存在；约一半的湿地和三分之一的红树林已经消失；90%的大型肉食鱼类业已灭绝，75%的海洋鱼类遭到过度捕捞或已经接近最大捕捞能力；20%的珊瑚礁消亡，另有20%受到严重威胁；物种灭绝的速度已达正常速度的100到1000倍；大部分干旱地区的农业用地已经严重退化；在我们每个人身体内都能找到几十种持久性有毒化学物质……

其次，要认识到当前人类活动的强度与自然活动的强度相比已经很大。在不知不觉中，人类活动严重地破坏了地球的臭氧层。我们使得大气中二氧化碳含量增长了三分之一，以致全球变暖、气候异常、冰川融化。我们在以与自然相同的速率固氮，恶果之一就是富营养化造成了至少150个海洋死亡区。我们消耗或破坏了自然界光合作用产出有机物的40%，而留给其它物种的已经太少。1960年到2000年，全球淡水使用量翻番，目前已经逼近所有河流流量的四分之一。科罗拉多河、黄河、恒河和尼罗河等河流在旱季断流而无水入海。我们生活的世界，与1900年，甚至与1950年相比，已经完全不同。

第三，要认识到，即使世界人口和经济停止增长，人类社会目前的活动也足以破坏地球的气候和动植物，更何况人类活动在迅猛增长。人类历史直到1950年，世界经济总量才第一次达到7万亿美元。但是今天，每5到10年全球产出就增加7万亿美元。到本世纪中叶，世界经济将再翻两番。这种经济增长再也不能重复过去的道路，而需要新的设计和新的技术。所有的一切——建筑业、制造业、能源生产、交通、森林与农业，都必须发生根本的变化。

最后，要认识到政治、技术和社会变革都需要时间。我们正在进行人类历史上最重要的一场竞赛，必须以大大超过世界经济增长的速度来改变我们的政治、技术和个人消费选择。我们只有深刻认识其紧迫性，采取空前的行动才有可能遏止自然资本的惊人退化。这是环境管理所面临的挑战。

为了应对这场竞赛，我们建立了一个新的学术领域，一个称为“环境”的交叉学科，对生物圈中人类社会和自然界的相互作用展开严谨、科学的研究。这个新领域产生的知识构成环境管理的基础。我们需要经过专业训练的一代人来从事环境管理，我们也需要将环境知识注入传统的职业，如商业、法律、科学和工程、医学等等，同时推动一场个人选择的革命，因为我们每个人在日常生活中同时是消费者、家庭成员、投资者、参与者、祷告者、工作者和投票者。所以，环境管理也应成为每一个公民最重要的责任。

我们对环境管理的认识，正处在一个必要而及时的范式转变过程中。1970年，当现代环境运动诞生的时候，环境运动的方式是对抗性的，把工商界当成敌人。今天，我们必须把合作放在首位，必须使工商界投入到这场运动中而不是把他们排除在外。我们人人都必须是环保主义者。

1970年，我们建立了一个独立的环境部门。今天，我们应该把所有经济部门变成环境友好的部门。每一个政府机构都必须是环境保护的机构。

1970年，是严加约束“污染者”的时候；今天，如果这些“污染者”能表明有更好的解决方法，我们可以将他们从法规的桎梏中解除出来。1970年，我们使用的是命令和控制；而今天，采取的是目标和激励。

1970年，我们反对；今天，我们应该支持。那时，我们发现问题之缘；今天，我们必须求得解决之道。那时，我们被动反应；今天我们必须主动预见。

1970年，技术被认为是将我们拖入泥淖的魔鬼；今天，我们还必须依靠技术，无论是软技术还是硬技术，带领我们走出这种困境。1970年，采取的是末端治理；今天，我们必须源头防范。

1970年，我们看到一个不加约束的市场把我们引向悬崖。今天，我们知道市场同时需要经济和环境目标的指引。这需要政府干预，以形成正确的价格——体现环境成本的价格。而反政府的理论家将会削弱我们为了共同的未来联合行动的能力。

1970年，目标是环境保护。今天的目标是可持续发展——要在相对贫困的国家实现可持续发展，因为除非贫困国家实现他们的发展和反贫困目标，否则我们无法永续利用生物圈。而谈到富裕国家的可持续发展，成功实现环境、经济和社会三重底线的目标要比实现GDP再增长3%来得更有意义。

1970年，环境运动限于国家范围内；而今天，环境运动是全球性的。环境污染全球化，物种跨国界转移，所以环境管理也必须“全球化”。环境必须进行“全球治理”。我们需要一个像世界贸易组织一样强大的世界环境组织。环境外交不再被边缘化，而要成为主流。但是归根结底，我们必须采取地方性的行动。因为我们每个人的生活是地方的，我们的行动也要因地制宜。

1970年，我们采取自上而下的措施；今天，我们必须鼓励创新的自下而上的草根方法，就像不用歌词、即兴和创新的绿色爵士乐。

1970年，我们过于崇尚精英；今天，我们必须强调正义和公平：国际平等、国内平等和男女平等，更有代际公平。我们已经成功地建立了一些保护区，但有时却忽视了贫困、少数族裔、受害者和土著居民。现在，他们的环境权必须得到维护。

1970年，环境保护的对象是物种；今天是生态系统。我们应该铭记：人类社会完全依靠自然生态系统提供的物质得以维持，但我们却经常忘记。我们终于必须认真对待奥尔多·利奥波德的生态伦理：那些保护生物群落的完整、稳定和美好的事物才应得到肯定。正像我们拥有自己的权利一样，生物社区同样拥有自身的权利。

1970年，我们期待政府的领导作用；今天，我们必须经常身体力行，无论政府支持与否。今天，工商界、科学家、消费者和环保主义者常常先于政府行动。我们不能坐等政府作为，而应助其先前。众所周知，民众推波，政府助澜。

1970年，我们来自火星^[原文为Mars，直译为火星，在希腊神话中亦有战神的意思。]；今天，我们应该来自金星^[原文为Venus，直译为金星，在希腊神话中亦有爱神的意思。]。那时，我们先将事物分解，然后制定理想的行动方案。今天，我们知道最重要的资源是人的动力——希望、关爱以及对自然和人类自身的感受。今天，我们需要布道者、哲学家、心理学家和诗人。W.S.梅文在一首诗中写道：地球末日/我希望种一棵树。另一首诗又说：我想告诉你森林是什么样子/我将不得不用一种早已遗忘的语言。华莱士·史蒂芬写道：最后言不，从此道是，未来所系，基于此是。尽管有关环境退化的预测骇人听闻，但我们确信我们终将赢得这场关系到人类未来的战争。的确如此。

现在我们又回到了起点，因为那个时代的重要方面，环境运动中所表现的非凡精神以及对深刻变革的普遍诉求，需要我们重燃和再建，而不是摒弃。从圣塔·芭芭拉的居民在1970年原油泄漏事件后不久给美国国会的信中，我们可以清楚地听到，“我们，因此决心行动。我们建议进行一场环境革命……今天我们在地球上开始新生，我们将重新开始”。今天，我们似乎已经远离了环境管理这个平淡的主题，但事实上这正是问题的核心。

何钢 译   施涵 崔丹丹 审校

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}